### ISSUE TITLE
Merge back taco-simulate and taco-simulate-server repos

### ISSUE THREAD

**Issue by busykai** [Microsoft/taco-simulate#3]
@TimBarham, we (CC: @albertinad) find it a major inconvenience to have `taco-simulate` and `taco-simulate-server` in different repositories. At least while it's in active development (at least on our side), let's merge back these two.

I remember that you envisioned these to foment the development of variety of app-hosts, but it just feels like an artificial and _very_ inconvenient separation at the moment. What you think? We currently have to employ `git subtree` to create a manageable development environment.

**Comment by TimBarham** [comment]
Hmmm, you shouldn't need to use `git subtree`. I find it very easy to work with this setup simply by doing the following:

In `taco-simulate-server` root folder:

```
$ npm link
```

In `taco-simulate` root folder:

```
$ npm link taco-simulate-server
```

Now `taco-simulate` is taking a dependency on your local version of `taco-simulate-server`, and changes made in the latter are immediately reflected in the former.

**Comment by busykai** [comment]
It's OK for the open source case, but not for our private fork (we would like to avoid fetching deps from a repo at the build time). It's not the question of what specific way of linking those two to use though.

There are other arguments for merging them back: 1. Developing a test suite is unnecessarily complicated (you need to test them together); 2. Changes to communication protocol require changes on both sides; 3. Linting and other repo-wide configurations have to be duplicated. I could think of few more if I think harder. However, I don't see a clear argument for diving them at this point in time. We can actually build two npm packages out of a single repo, so that part does not have to change.
